pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/nehakalegit/Project2-CI-CD-Pipeline-Automation.git'
            }
        }

        stage('Verify App') {
            steps {
                sh 'ls -la app/'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Deploy using Ansible') {
            steps {
                dir('ansible') {
                    sh 'ansible-playbook -i inventory.ini deploy.yml'
                }
            }
        }
    }
}
