pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = "us-east-1"
    }

    stages {

        stage('Show Workspace') {
            steps {
                sh 'ls -R'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-access-key']]) {
                    sh '''
                    cd ci-cd-pipeline-project/terraform
                    terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-access-key']]) {
                    sh '''
                    cd ci-cd-pipeline-project/terraform
                    terraform plan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-access-key']]) {
                    sh '''
                    cd ci-cd-pipeline-project/terraform
                    terraform apply -auto-approve
                    '''
                }
            }
        }

        // ✅ Get EC2 IP
        stage('Get IP') {
            steps {
                script {
                    env.EC2_IP = sh(
                        script: "cd ci-cd-pipeline-project/terraform && terraform output -raw public_ip",
                        returnStdout: true
                    ).trim()
                }
            }
        }

        // ✅ Create dynamic inventory
        stage('Create Inventory') {
            steps {
                sh """
                echo "[web]" > inventory.ini
                echo "${EC2_IP} ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/keypairvirginia.pem" >> inventory.ini
                """
            }
        }

        // ✅ NEW: Wait for EC2 to be ready
        stage('Wait for Instance') {
            steps {
                sh 'echo "Waiting for EC2 to initialize..."'
                sh 'sleep 60'
            }
        }

        // ✅ Deploy Ansible
        stage('Deploy Ansible') {
            steps {
                sshagent(['keypair']) {
                    sh """
                    export ANSIBLE_HOST_KEY_CHECKING=False
                    cd ci-cd-pipeline-project/ansible
                    ansible-playbook -i ../../inventory.ini deploy.yml
                    """
                }
            }
        }
    }
}
