pipeline {
    agent any

    stages {

        stage('Terraform Init') {
            steps {
                sh '''
                cd ci-cd-pipeline-project/terraform
                terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                cd ci-cd-pipeline-project/terraform
                terraform plan
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                cd ci-cd-pipeline-project/terraform
                terraform apply -auto-approve
                '''
            }
        }

        stage('Deploy using Ansible') {
            steps {
                sh '''
                cd ci-cd-pipeline-project/ansible
                ansible-playbook -i inventory.ini deploy.yml
                '''
            }
        }
    }
}
