- name: Deploy Static Website
  hosts: web
  become: true

  tasks:

    - name: Wait for system to be ready
      pause:
        seconds: 30

    - name: Wait for yum lock
      shell: |
        while sudo fuser /var/run/yum.pid >/dev/null 2>&1; do
          echo "Waiting for yum lock..."
          sleep 5
        done
      changed_when: false

    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Enable nginx repo (Amazon Linux)
      command: amazon-linux-extras enable nginx1
      ignore_errors: yes

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy HTML file
      copy:
        src: ../app/index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
