- name: Deploy Static Website
  hosts: web
  become: true

  tasks:

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy HTML file
      copy:
        src: ../app/index.html
        dest: /usr/share/nginx/html/index.html
